/* NEON SHIFT: standalone Canvas platform runner */
const C=document.getElementById('game'), ctx=C.getContext('2d'), W=1280,H=720;
const $=id=>document.getElementById(id), ui={menu:$('menu'),pause:$('pause'),complete:$('complete'),over:$('over'),hud:$('hud')};
let state='START', last=0, keys={}, game, muted=false, audio;
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n)), overlap=(a,b)=>a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y;
function tone(f,d=.08,type='sine',vol=.04){if(muted)return;try{audio||=new AudioContext();let o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.value=f;g.gain.setValueAtTime(vol,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+d);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+d)}catch(e){}}
class Player{constructor(){this.x=100;this.y=480;this.w=32;this.h=48;this.vx=0;this.vy=0;this.onGround=false;this.lives=3;this.inv=0;this.trail=[];this.face=1;this.shift=0;this.anim=0}
 update(dt){let left=keys.a||keys.arrowleft,right=keys.d||keys.arrowright;let move=(right?1:0)-(left?1:0);this.vx+=move*1500*dt;this.vx*=Math.pow(.0005,dt);this.vx=clamp(this.vx,-310,310);if(move)this.face=move;if((keys.w||keys.arrowup||keys.space)&&this.onGround){this.vy=-590;this.onGround=false;tone(440,.09,'square')}this.vy+=1450*dt;this.vy=Math.min(this.vy,780);this.x+=this.vx*dt;this.x=clamp(this.x,0,game.len-this.w);this.y+=this.vy*dt;this.onGround=false;for(const p of game.platforms){if(!active(p)||this.vy<0)continue;let oldBottom=this.y-this.vy*dt+this.h;if(this.x+this.w>p.x&&this.x<p.x+p.w&&this.y+this.h>=p.y&&oldBottom<=p.y+12){this.y=p.y-this.h;this.vy=0;this.onGround=true;if(p.moving)this.x+=p.dx*dt}}this.inv=Math.max(0,this.inv-dt);this.shift=Math.max(0,this.shift-dt);this.anim+=dt*10;if(Math.abs(this.vx)>130&&Math.random()<dt*25)this.trail.push({x:this.x+this.w/2,y:this.y+30,life:.45,c:game.dim?'#ff593d':'#4ff4ff'});this.trail.forEach(t=>t.life-=dt);this.trail=this.trail.filter(t=>t.life>0);if(this.y>H+140)damage();}}
function active(o){return o.dim===undefined||o.dim===game.dim}
function addSection(n){let base=(n-1)*1450, hard=n-1, groundY=600;game.platforms.push({x:base,y:groundY,w:720,h:35});game.platforms.push({x:base+790,y:groundY,w:660,h:35});let layouts=[[{x:760,y:505,w:125,dim:1},{x:990,y:455,w:130,dim:0},{x:1170,y:400,w:150,dim:1}], [{x:690,y:490,w:130,dim:0},{x:875,y:420,w:120,dim:1},{x:1070,y:500,w:145,dim:0}], [{x:730,y:450,w:110,dim:1},{x:910,y:370,w:130,dim:0},{x:1110,y:450,w:130,dim:1}]][n%3];layouts.forEach(p=>game.platforms.push({...p,x:p.x+base,y:p.y,h:18}));if(n>1)game.platforms.push({x:base+430,y:480,w:120,h:18,moving:true,range:90,phase:Math.random()*6,dim:n%2});for(let i=0;i<5+hard;i++)game.shards.push({x:base+170+i*190,y:490-(i%3)*65,dim:(i+n)%3?undefined:n%2,got:false});for(let i=0;i<1+hard;i++)game.enemies.push({x:base+480+i*230,y:565,w:30,h:30,type:i%4,dir:1,base:base+440+i*230,dim:i===2?n%2:undefined,dead:0});game.obstacles.push({x:base+620,y:568,w:30,h:32,dim:n%2});game.checkpoints.push({x:base+1300,y:525,used:false});}
function buildLevel(n){game={level:n,len:1450*n,dim:0,score:game?.score||0,energy:game?.energy||0,platforms:[],shards:[],enemies:[],obstacles:[],checkpoints:[],camera:0,time:0,shake:0,flash:0};for(let i=1;i<=n;i++)addSection(i);game.p=new Player();}
function start(){buildLevel(1);state='PLAYING';ui.menu.classList.add('hidden');ui.over.classList.add('hidden');ui.hud.classList.remove('hidden');tone(240,.15,'sawtooth');}
function reset(){start()}
function shift(){let p=game.p;if(p.shift>0||state!=='PLAYING')return;game.dim=1-game.dim;p.shift=.9;game.flash=.38;game.score+=25;tone(game.dim?160:520,.18,'sawtooth',.06);for(let i=0;i<30;i++)particles.push({x:p.x+16,y:p.y+25,vx:(Math.random()-.5)*400,vy:(Math.random()-.5)*400,life:.45,c:game.dim?'#ff5a35':'#57efff'});}
let particles=[];function damage(){let p=game.p;if(p.inv>0)return;p.lives--;p.inv=1.5;game.shake=.35;game.flash=.18;tone(95,.28,'sawtooth',.08);if(p.lives<=0){state='GAME_OVER';let high=Math.max(+localStorage.neonShiftHigh||0,game.score);localStorage.neonShiftHigh=high;$('stats').innerHTML=`FINAL SCORE: ${game.score}<br>HIGH SCORE: ${high}<br>LEVEL REACHED: ${game.level}<br>ENERGY COLLECTED: ${game.energy}`;ui.over.classList.remove('hidden');ui.hud.classList.add('hidden');tone(60,.7,'sawtooth',.1)}}
function update(dt){if(state!=='PLAYING')return;game.time+=dt;game.score+=Math.floor(dt*4);game.platforms.forEach(p=>{if(p.moving){let old=p.x;p.x=p.x0??p.x;p.x0??=p.x;p.x=p.x0+Math.sin(game.time*1.5+p.phase)*p.range;p.dx=(p.x-old)/dt}});game.p.update(dt);let p=game.p;game.enemies.forEach(e=>{if(e.dead){e.dead-=dt;return}if(!active(e))return;let sp=55+game.level*13;if(e.type===1&&Math.abs(e.x-p.x)<250)e.dir=Math.sign(p.x-e.x)||1;else if(e.type===3)e.dir=Math.sin(game.time*3+e.x)*1;else if(e.x<e.base-90||e.x>e.base+90)e.dir*=-1;e.x+=e.dir*sp*dt;e.y=570+Math.sin(game.time*3+e.x)* (e.type===3?22:0);if(overlap(p,e))damage()});game.obstacles.forEach(o=>{if(active(o)&&overlap(p,o))damage()});game.shards.forEach(s=>{if(!s.got&&active(s)&&overlap(p,{x:s.x-10,y:s.y-10,w:20,h:20})){s.got=true;game.energy++;game.score+=100;tone(740,.09,'triangle');for(let i=0;i<8;i++)particles.push({x:s.x,y:s.y,vx:(Math.random()-.5)*180,vy:(Math.random()-.5)*180,life:.5,c:'#ffe960'})}});game.checkpoints.forEach(c=>{if(!c.used&&p.x>c.x){c.used=true;game.score+=300;tone(660,.18,'sine')}});if(p.x>game.len-95){if(game.level>=5){state='LEVEL_COMPLETE';$('completeText').textContent='REALITY CORE STABILIZED — YOU WIN!';ui.complete.classList.remove('hidden');setTimeout(()=>{state='START';ui.complete.classList.add('hidden');ui.menu.classList.remove('hidden');ui.hud.classList.add('hidden')},3500)}else{state='LEVEL_COMPLETE';$('completeText').textContent=`LEVEL ${game.level} COMPLETE`;ui.complete.classList.remove('hidden');tone(880,.35,'triangle');setTimeout(()=>{let sc=game.score,en=game.energy;buildLevel(game.level+1);game.score=sc;game.energy=en;state='PLAYING';ui.complete.classList.add('hidden')},1900)}}game.camera+=((clamp(p.x-W*.32,0,game.len-W)-game.camera)*Math.min(1,dt*5));game.shake=Math.max(0,game.shake-dt);game.flash=Math.max(0,game.flash-dt);particles.forEach(q=>{q.x+=q.vx*dt;q.y+=q.vy*dt;q.life-=dt});particles=particles.filter(q=>q.life>0)}
function draw(){let d=game?.dim||0, cam=game?.camera||0;ctx.clearRect(0,0,W,H);let grad=ctx.createLinearGradient(0,0,0,H);grad.addColorStop(0,d?'#270512':'#06082a');grad.addColorStop(1,d?'#09020b':'#020518');ctx.fillStyle=grad;ctx.fillRect(0,0,W,H);if(game){ctx.save();ctx.translate((Math.random()-.5)*game.shake*25,0);for(let i=0;i<35;i++){let x=(i*113-cam*.18)%1500;ctx.fillStyle=d?'#ff3b4a22':'#527bff22';ctx.fillRect(x,150+(i*47)%350,2,120)}ctx.strokeStyle=d?'#ff426844':'#3e9cff44';ctx.lineWidth=1;for(let y=430;y<720;y+=35){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()}let X=x=>x-cam;game.platforms.forEach(p=>{if(!active(p))return;ctx.fillStyle=d?'#e7355c':'#4775ff';ctx.shadowBlur=16;ctx.shadowColor=ctx.fillStyle;ctx.fillRect(X(p.x),p.y,p.w,p.h);ctx.shadowBlur=0;ctx.fillStyle='#d7ffff';ctx.fillRect(X(p.x),p.y,p.w,2)});game.checkpoints.forEach(c=>{ctx.fillStyle=c.used?'#62ffb0':'#ffe45c';ctx.fillRect(X(c.x),c.y,4,75);ctx.fillRect(X(c.x)+4,c.y,28,15)});game.obstacles.forEach(o=>{if(active(o)){ctx.fillStyle='#ff315a';ctx.beginPath();ctx.moveTo(X(o.x),o.y+o.h);ctx.lineTo(X(o.x+o.w/2),o.y);ctx.lineTo(X(o.x+o.w),o.y+o.h);ctx.fill()}});game.shards.forEach(s=>{if(!s.got&&active(s)){ctx.save();ctx.translate(X(s.x),s.y);ctx.rotate(game.time*3);ctx.fillStyle='#ffe65c';ctx.shadowBlur=18;ctx.shadowColor='#ffe65c';ctx.fillRect(-7,-7,14,14);ctx.restore()}});game.enemies.forEach(e=>{if(!e.dead&&active(e)){ctx.fillStyle=['#e448ff','#ff8150','#66ffdd','#ff254e'][e.type];ctx.shadowBlur=12;ctx.shadowColor=ctx.fillStyle;ctx.fillRect(X(e.x),e.y,e.w,e.h);ctx.fillStyle='#061022';ctx.fillRect(X(e.x)+6,e.y+8,18,5)}});let p=game.p;p.trail.forEach(t=>{ctx.globalAlpha=t.life*1.5;ctx.fillStyle=t.c;ctx.fillRect(X(t.x)-5,t.y-5,10,10)});ctx.globalAlpha=p.inv&&Math.floor(p.inv*12)%2?0.25:1;ctx.fillStyle=d?'#ff7358':'#55efff';ctx.shadowBlur=25;ctx.shadowColor=ctx.fillStyle;ctx.fillRect(X(p.x),p.y,p.w,p.h);ctx.fillStyle='#ecffff';ctx.fillRect(X(p.x)+(p.face>0?19:4),p.y+12,9,6);ctx.fillStyle='#151331';ctx.fillRect(X(p.x)+4,p.y+40,9,8);ctx.fillRect(X(p.x)+19,p.y+40,9,8);ctx.globalAlpha=1;ctx.restore();if(game.flash){ctx.fillStyle=(d?'#ff3760':'#4ef4ff');ctx.globalAlpha=game.flash*.35;ctx.fillRect(0,0,W,H);ctx.globalAlpha=1}}else{ctx.fillStyle='#06102b';ctx.fillRect(0,0,W,H)}renderHUD()}
function renderHUD(){if(!game)return;$('score').textContent=String(game.score).padStart(6,'0');$('high').textContent=String(Math.max(+localStorage.neonShiftHigh||0,game.score)).padStart(6,'0');$('energy').textContent=game.energy;$('health').textContent='♥'.repeat(game.p.lives)+'♡'.repeat(3-game.p.lives);$('level').textContent=game.level;$('reality').textContent=game.dim?'B':'A';$('cooldown').textContent=game.p.shift?`${game.p.shift.toFixed(1)}s`:'READY'}
function loop(t){let dt=Math.min(.033,(t-last)/1000||0);last=t;update(dt);draw();requestAnimationFrame(loop)}requestAnimationFrame(loop);
addEventListener('keydown',e=>{let k=e.key.toLowerCase();if(['arrowleft','arrowright','arrowup',' ','a','d','w','q','p','r'].includes(k))e.preventDefault();keys[k===' '?'space':k]=true;if(k==='q')shift();if(k==='p'&&state==='PLAYING'){state='PAUSED';ui.pause.classList.remove('hidden')}else if(k==='p'&&state==='PAUSED'){state='PLAYING';ui.pause.classList.add('hidden')}if(k==='r'&&state==='GAME_OVER')reset()});addEventListener('keyup',e=>keys[e.key.toLowerCase()===' '?'space':e.key.toLowerCase()]=false);$('play').onclick=start;$('restart').onclick=reset;$('how').onclick=()=>{$('instructions').style.display=$('instructions').style.display==='none'?'grid':'none'};$('sound').onclick=()=>{muted=!muted;$('sound').textContent='SOUND: '+(muted?'OFF':'ON')};
